### ISSUE TITLE
Provide a mechanism to regularly update prefixes in json-ld contexts

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#113]
For example, this

https://github.com/geneontology/minerva/blob/master/minerva-core/src/main/resources/amigo_context_gen.jsonld

is derived from the GO dbxrefs-yaml

This was done a while ago - no EnsemblPlants. And since minerva depends on a json-ld context for expansion of any ID it gets from Noctua, ensembl plants can't be used.

the prefixcommons biocontexts repo https://github.com/prefixcommons/biocontext/tree/master/registry has scripts for generating the ld contexts from sources like GO

**Comment by kltm** [comment]
@elserj It would be easy enough then to just make changes here and recompile minerva (`./build-cli.sh` at the top level). If you switch to the `issue-430` branch of Noctua it supports having an arbitrary minerva-cli.jar as a variable (take a look at the example `startup.yaml`s).

**Comment by elserj** [comment]
So, rather than switch to a new branch of noctua, I tried to cherry pick the commit that added the ability to use external minerva-cli.jar (cd33c8a842b7f9379680666ac16c289eec6a3633), and added the following to startup.yaml:
MINERVA_JAR:
  comment: Select an external miverva-cli.jar file
  type: file
  value: /data/www/planteome_dev/minerva/minerva-cli/bin/minerva-cli.jar

And it seems to get picked up.  As the first line when running node_modules/.bin/gulp run-minerva has the new jar file referenced, but it just stops at the following line after loading the ontologies:
INFO  (StartUpTool:320) Start initializing Minerva

The next lines in a normal startup should be:
(Configuration:256) com.bigdata.journal.AbstractJournal.historicalIndexCacheCapacity=60
and then continues until I get the "Started SelectChannelConnector"

So, it looks like it's not finding the files in the jar properly or something.  Did I miss something?

**Comment by balhoff** [comment]
Hi, how long did you wait after that message? If you're using the `--arachne` option for Minerva then it will do some extra work at that point. It should only take about 40 seconds—unless you are getting tight on heap space.

**Comment by elserj** [comment]
I didn't change any other options.  I've now left it for about 10 minutes, still sitting there.  I did just check the output of "top" and the minerva process is using 2 cores and 10.6GB VIRT and 4.5GB RES RAM, so I guess it's doing something, but the built in minerva-cli.jar passes this step in less than a second.

Machine has 64GB RAM, -Xmx option is set to 4G.

The only change I made to the minerva code before I ran ./build-cli.sh was to add some lines to the amigo_context_gen.jsonld file.  I did not try building before I made those changes.

**Comment by balhoff** [comment]
I think 4G is going to be too small. This version has some reasoner code that wasn't in the previous embedded jar. You're stuck in garbage collection. If you increase to 12G it will hopefully start up quickly.

**Comment by elserj** [comment]
Thanks, that does seem to be the issue.  Upped it to 24GB and it does now get past it.  Takes longer, but does at least continue now.

**Comment by kltm** [comment]
It certainly doesn't run in 4GB on my machine, which is sort of the whole `issue-430` branch of noctua right now.

@elserj I think it would probably be easier to just switch over to `issue-430` for noctua as it already tracks master and will eventually merge back in once those issues are fully resolved.

**Comment by balhoff** [comment]
Back to the original topic of this issue, @cmungall do you want to have the context file be a command-line option? These seem to all be hardcoded right now:

```java
static CurieMappings loadDefaultMappings() {
		final Map<String, String> curieMap = new HashMap<String, String>();
		loadJsonldResource("obo_context.jsonld", curieMap);
		loadJsonldResource("monarch_context.jsonld", curieMap);
		loadJsonldResource("amigo_context_gen.jsonld", curieMap);
		loadJsonldResource("amigo_context_manual.jsonld", curieMap);
		return new CurieMappings.SimpleCurieMappings(curieMap);
	}
```

Is there something Minerva needs to support better vs. someone adding a line to the context and recompiling?

**Comment by cmungall** [comment]
Yes, should be a CLI, but let's leave these in as defaults. If the user specifies *no* contexts, use the defaults. If the user specifies one or more contexts, then ignore defaults.

I want to avoid disrupting existing configurations.
