### ISSUE TITLE
Add /status API call

### ISSUE THREAD

**Issue by balhoff** [geneontology/minerva#167]
For use in uptime monitoring.

**Comment by kltm** [comment]
To fill this out a little bit, the idea is to have a /status route to allow external clients to check on the internal state of minerva. For reference, see:

http://barista-dev.berkeleybop.org/status
http://noctua-dev.berkeleybop.org/status

Minerva has occasional "exotic" outages, most recently it had apparently been eating its logs for about a week, with nobody the wiser, until it suddenly stopped responding (502 proxy error). Ideally, the /status route exposes some of minerva's internal state as well in a useful way. A (possibly hard) example would be editing and reading a model on disk in a separate location to confirm normal operation. Simpler examples would be a running count of requests served, last request served, last user served, etc.

**Comment by goodb** [comment]
@kltm do you intend to make or have some one make a dashboard app that would make use of this service?  If so, maybe spec it out in a little more detail?  

A quick stateless 'are you alive' service ought to be really easy.  It would take a little more time to set up request logging, but also not a big issue if you think it would be valuable.

**Comment by kltm** [comment]
The "console" is currently: https://status.geneontology.org/ , which is the main method we have for now for seeing how things are doing. We also make some use of Monit (https://mmonit.com/monit/), which would allow things like earlier alerts when things started going bad, etc. (There are some other marginal monitors as well.)
That said, the act of having self-examination in code I think is a useful one, especially in complicated systems such as this, where we had an ongoing event over a week that has affected our ability to determine what the underlying issue is/was. Anything that is capable of directly consuming (and therefore losing) user time should probably have more of that kind of mechanism built in.

**Comment by kltm** [comment]
Also, note: https://github.com/geneontology/minerva/issues/104
