### ISSUE TITLE
NOT gpad lines doubled

### ISSUE THREAD

**Issue by goodb** [geneontology/minerva#214]
e.g. http://noctua-dev.berkeleybop.org/editor/graph/gomodel:5c533d1100000051

produces 2 identical lines:

!gpa-version: 1.1
FB	FBgn0015926	enables|NOT	GO:0019003	pmid:17	ECO:0007651			20190201	GO_Central		contributor=http://orcid.org/0000-0002-7334-7852|noctua-model-id=gomodel:5c533d1100000051|model-state=development
FB	FBgn0015926	enables|NOT	GO:0019003	pmid:17	ECO:0007652			20190201	GO_Central		contributor=http://orcid.org/0000-0002-7334-7852|noctua-model-id=gomodel:5c533d1100000051|model-state=development

**Comment by balhoff** [comment]
I see two different ECO codes there. 😀

**Comment by goodb** [comment]
There is only one used in the model - 'automatically integrated combinatorial computational evidence used in manual assertion'.  

It looks like it gets that and its parent ECO term.  Is that desired ?

**Comment by balhoff** [comment]
Oh I see, I will check it out.

**Comment by balhoff** [comment]
This model is gone.

**Comment by goodb** [comment]
I made a new one in non-dev noctua.  http://noctua.geneontology.org/editor/graph/gomodel:5c4605cc00000315  

The issue seems specific to the evidence code 'automatically integrated combinatorial computational evidence used in manual assertion' not the presence of the NOT.

**Comment by balhoff** [comment]
This is a result of having switched to using `eco-base`, which is not pre-reasoned. 'automatically integrated combinatorial computational evidence used in manual assertion' has no asserted superclass; instead it has an equivalentClass definition. So the "actual" superclass is inferred as a non-redundant type for the evidence instance.

This problem will be fixed by switching to `eco-basic`, which is happening soon in go-lego. Alternatively it would also be fixed by pre-reasoning go-lego, which hopefully will also happen soon.

**Comment by vanaukenk** [comment]
@balhoff - has the switch to eco-basic happened?  If so, and you think this ticket can be closed, please feel free to do so.

Thx.

**Comment by balhoff** [comment]
Yes.
