### ISSUE TITLE
Minerva should tag all entities in tbox with biolink categories on startup

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#231]
Note in future we can potentially rely on this being done ahead of time (e.g. neo here https://github.com/geneontology/neo/pull/40), but for us to progress it would be good if this was done as a postprocessing step after loading go-lego, to guarantee it will be there.

For this to work, Minerva needs to be supplied a lookup table of rootish OBO nodes to categories. (Note this is very similar to what scigraph does).

See https://github.com/biolink/biolinkml/issues/36 for broader discussion

**Comment by balhoff** [comment]
How will this need to be used by the application? Asking because an alternative would be a small set of RDF rules (one for each category) that infers a relation between every instance and its BioLink category. In this case the results would be available in the inferred graph. Is that useful @goodb?

A rule would be something like:

`[(?x rdf:type UBERON:0001062) -> (?x biolink:has_category biolink:AnatomicalEntity)]`

**Comment by goodb** [comment]
@balhoff the intention is a precomputation of the typing inferences so that basically anytime anyone gets a hold of any of the ontology terms, they can access the biolink type without needing to run a reasoner.  

This would be used by Tremayne's js client code to organize interface elements based on bl-type for nodes and would also be used by the shex validator.  For the shex use case, I think your solution would work as long as we commit to running the reasoner for each model validation - as we probably want to anyway.  (Note that on my laptop at least, the reasoner takes about 30 seconds to classify one go-cam model from the Reactome collection.)  

I think there are other uses outside the context of Noctua with basically the same flavor - easily accessing upper level type information without reasoner access.

**Comment by balhoff** [comment]
Do we want to use this tbox/biolink index to tag all individuals coming into Minerva, so that this is present in the asserted graph?

**Comment by goodb** [comment]
@balhoff I think that would be a good approach.  That way anyone that downloaded one of the model files could apply the shex directly.  We could even consider utilizing a javascript shex validator in that case..

**Comment by goodb** [comment]
@balhoff @cmungall @kltm is this still the plan?  It seems that the shex work drifted away from this approach.

**Comment by tmushayahama** [comment]
@balhoff @cmungall @goodb @kltm @lpalbou  yesss, this will be awesome. For response presentation, the value is not one-to-one, so a range like named json or array will be ideal. For example a macromolecular complex is both a CC and a macromolecular, so the type will be an array (range = [GoProteinContainingComplex, GoCellularComponent] or simply ['GO:0032991', 'GO:0005575']

Another approach which will be faster and not affect the current performance and workflow on your side is lazy metadata kinda loading. Loading the bare minimums of the model through minerva at first and have the client ask more through api for extra or external metadata which is not in the house. As long as it is a bulk call. Example, getTypes(<list> classes), or fillTypes(<bbop-graph> subgraph) etc 
A typical use case for a client

- Load the graph 
- Traverse through the graph and gather all the individuals you want more info
- Send a bulk minerva requests for biolink categories or type and extra info as needed

However, the category should be the one defined in GO Shapes
So the function idea is already on go-shapes https://github.com/geneontology/go-shapes/blob/6d7a714c45bd793a3a9e19ddfb1719fdffb107e3/python/gocam_validator.py#L129 

### Why API, a lazy loading approach is favorable
The minerva graph is loaded or rebuild frequently to the client whenever there is a change/edit delete, so a thin response is necessary. This function call which replaces the old model is easier as it rerender everything than trying to merge.
```
minervaManager.register('rebuild', (resp) => {
     rebuild(resp);
}, 10)
```

Anyway, currently in Noctua Form for performance boost, it stores the categories in a local lookup table/db so that the subsequent 'rebuilds', if the category was resolved it doesn't ask for it again.

**Comment by tmushayahama** [comment]
I have put this as one of the high priority because NF and ART really need this to work and now cannot handle the demand using the hacky way of calling neo  1000+ to figure out the categories. 

As an example, given **"CL:0002434"** NF on startup sends a preparse function of 11 requests for this individual inorder to store these in a local database lookup for future use when the graph is actually being parsed.
 
CL:0002434
-  GoProteinContainingComplex = false,
-  GoCellularComponent = false,
-  GoBiologicalProcess = false,
-  GoMolecularFunction =false,
-  GoMolecularEntity = false,
-  GoChemicalEntity = true,
-  GoEvidence = false,
-  GoCellTypeEntity = true,
-  GoAnatomicalEntity = false,
-  GoOrganism = false,
-  GoBiologicalPhase = false,

So 100 nodes (including evidence nodes is like 1100 NEO requests) . All requests promises have to be resolved before NF continue, otherwise there is no parser.

**Comment by vanaukenk** [comment]
@tmushayahama @kltm 
Can we discuss on tomorrow's software call or on a separate call on Friday, 9/6?

**Comment by goodb** [comment]
@cmungall it seems like this idea (with biolink) has fallen by the wayside.  Can we close this ticket as wont fix or do we need to revisit?

**Comment by tmushayahama** [comment]
@goodb ohhh,, I wanted this so badly. Any other alternatives?
