### ISSUE TITLE
Add "reset" "model" command to Minerva edit API

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#355]
Add "reset" "model" command to Minerva edit API.

This reset command would revert the internal model state ("unsaved") to that which is found on disk.

It would be patterned as the "store" operation (https://github.com/berkeleybop/bbop-manager-minerva/wiki/MinervaRequestAPI#peripheral-operations).

**Comment by goodb** [comment]
When you say 'on disk' I think you mean 'stored in blazegraph' but lets be sure.  We have three states that I know about right now.  

1. The model sitting in github and as text on the server disk.  
2. The model that is in the live blazegraph running while the server is running.  This model may have been edited and saved any number of times while minerva is running.  These models only align with the models in 1. either when the system is started up or after a command has been issued to dump them all out. 
3. The models that have been edited but have not been saved.  These live in OWL-API ontology models in memory.  

Okay for this ticket to mean 'undo all changes since last save to running blazegraph'?  Which would most likely happen by simply deleting the model in question from the in-memory collection and then reloading from blazegraph.  

Yes?

**Comment by kltm** [comment]
My understanding is that when minerva gets a "store" command, one of the internal models (blazegraph?) flushes to disk (along with the destruction of undo/redo on the owl side?). With this in my mind, "on-disk" is then whatever the last saved state on disk was that is pushed to github. Since I have a not-too-clear understanding of the internals of minerva at this point, any functional proxy for that concept is fine by me. 
I would assume that deleting the internal representation(s?) and reloading from a "clean" source would be fine? I'm out of my depth here, but I'm happy to continue trying to explain what I mean by "reset", which will usually be couched in terms of what I would find on disk--the pull-the-power-cord-from-the-wall routine.

**Comment by goodb** [comment]
Unless I am missing something, which is certainly possible, nothing is written to a file other than the blazegraph journal unless the minerva-cli command-line interface is used with the --dump-owl-models command.  If you pull the power cord and restart by rebuilding the journal from the files, you would lose content in the journal.  If you started up from the journal file, it ought to be fine.  

I just want to be sure we are all on the same page here.  I think the correct function for the ART use case is a reset to the last saved version of the model and this would correspond to the one in running blazegraph journal. 

If we want to maintain synchrony between blazegraph and the folder containing the models we could do that, but I don't see that happening right now.

**Comment by kltm** [comment]
After talking to @goodb , let me amend/correct what I have above.
Currently, the way things get to disk is the command `export-all`, emitted periodically from a client in a cron job; this is wired the same as `--dump-owl-models`, dumping everything we have in blazegraph to disk.
The "store" command is what is used to get the contents of the currently-under-edit in-memory owl model into the blazegraph; the blazegraph being minerva's source of truth.
Given that, deleting the owl in-memory model and having it re-pull from blazegraph should be all that is needed for a "reset" command.

**Comment by goodb** [comment]
this works
