### ISSUE TITLE
Backup label lookup system fails in non-GO contexts

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#36]
The current fallback system, if a label cannot be found in the ontology, is to check external source, which currently means a GOlr instance. It seems to first search "ontology_class" and then "bioentity". While this is fine for the GO, the Monarch instances do not have a "bioentity" field, causing a failure when Solr returns an error.

Since Monarch does have ontology_class and GO uses the neo load for autocomplete (so no bioentity), an immediate solution could be just removing that. (Although I'm not sure if there is an implication there for seeding.) 
More complicated solutions could include run-time configurable field selections per Solr resource, but that seems like the wrong direction. Moreover since the external lookup may not be necessary with labels loaded in neo.

@DoctorBud for Monarch

**Comment by cmungall** [comment]
Ideally the fallback system is not necessary, this is because we have an unusual division of responsibilities. The main reason we require it is because we have no guarantee that the solr index used for ontology class autocomplete was loaded using the exact same versionIRIs in the import chain as what is loaded into minerva (if minerva was in charge of providing autocompletes then the worlds are guaranteed identical).

There will be requirements in future for doing wider lookups for entities in  the wider world, for example to pubmed, to any sequence in NCBI... but here we don't want to limit it it a solr we control, we'd want an extensible set of adapters for various external services

**Comment by hdietze** [comment]
As a *temporary* fix, I have created a separate Golr client for a Monarch Golr instance, which doesn't query for bioentities.
Usage: `--monarch-labels URL`
