### ISSUE TITLE
JSON should not be embedded inside OWL

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#38]
There is an undocumented http://geneontology.org/lego/json-model annotation inside all the models that has a JSON string. Is this a temporary measure? We should have a milestone for when this will be removed.

**Comment by cmungall** [comment]
I love how the output of `--owl-lego-to-json` contains a copy of itself (but only one deep? If we keep roundtripping does it recursively deepen to keep N copies of itself?)

**Comment by hdietze** [comment]
A quick back story of why we added it. It is a **dirty dirty** quick hack.
The intimidate reason was the need to add the json representation to Golr without the copying of 'all' mapping code (incl. curie mapping) into owltools (from minerva)
Since then it also simplified the loading code for quick model index on the front page (via the file alteration monitor)

**Comment by hdietze** [comment]
The minerva server will ignore the JSON during load, as it skips all axioms tagged with a specific annotation (derived). See:
 * org.geneontology.minerva.ModelReaderHelper
 * org.geneontology.minerva.ModelWriterHelper
