### ISSUE TITLE
Add two new annotation extension relations to gpad-extensions.rq

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/minerva#406]
@balhoff 

Please add these two new annotation extension relations from RO to the gpad-extensions.rq file so we can start exporting them from GO-CAM models.
Thx.

http://purl.obolibrary.org/obo/RO_0002490
http://purl.obolibrary.org/obo/RO_0002491

@suzialeksander @ukemi @dustine32

**Comment by balhoff** [comment]
@vanaukenk I think your test model may need a matching PMID added on the `existence overlaps` edge.

**Comment by ukemi** [comment]
MGI has annotation using RO_0002491.

**Comment by ukemi** [comment]
MGI:MGI:97621 |   | RO:0001025 | GO:0000775 | MGI:MGI:5882483\|PMID:26919979 | ECO:0000314 |   |   | 2021-06-02 | MGI | RO:0002491(GO:0000236)\|RO:0002491(GO:0000278) | creation-date=2020-05-05\|modification-

**Comment by ukemi** [comment]
There are several annotations in the MGI GPAD file that use RO:0002491 in annotation extensions.

**Comment by dustine32** [comment]
Ah, the relation "existence starts and ends during" isn't in the current noctua-dev MGI models because they were [generated](https://github.com/geneontology/noctua-models/pull/203) before @vanaukenk's [relations.py change](https://github.com/biolink/ontobio/pull/584/files) was merged.

I did a quick before-and-after test generating the MGI:MGI:97621 model with the latest `ontobio` vs the version used on 2021-08-09. The current `ontobio` emits the relation while the older code does not. So, this will be fixed when I regenerate the MGI models tomorrow.

**Comment by ukemi** [comment]
I still don't see these in the new file that Dustin released.

**Comment by ukemi** [comment]
My bad! I was looking for the RO identifers:

MGI	MGI:88311	located_in	GO:0005737	PMID:23541922	ECO:0000314			20200429	MGI	existence_overlaps(GO:0051331)	model-state=production|contributor=https://orcid.org/0000-0002-9796-7693|noctua-model-id=gomodel:5e72450500002902

This one is ready to go to production.

**Comment by ukemi** [comment]
Is it in production? I haven't been closing them until the changes go to production. I have a column for that in the MGI imports project.

**Comment by ukemi** [comment]
I fear that if we close them without making sure they went over the fence, we may miss some. Maybe it's not a  valid fear.
