### ISSUE TITLE
Noctua model (correct in Annotation Preview) not making it to SGD GPAD

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/minerva#494]
SGD has an ISS (like #328 this is a mixed model, to a human protein) that's not appearing at our end.  Seems to be missing from the noctua_sgd.gpad but I *think* the ttl files exist (?) https://github.com/geneontology/noctua-models/blob/ef1c8565edc4a87f5ef9b059a0ac6f55e08891a2/models/61f34dd300000776.ttl
The C and P from this model seem to be ok, only the mixed part (F) is missing/lost. 

@kltm just guessing this is the right repo based on the other ticket

**Comment by suzialeksander** [comment]
Correct, I don't know why the one we're expecting isn't coming out (was that a question for me?)

**Comment by ukemi** [comment]
It must be filtered downstream of minerva. Here is the GPAD:
!gpa-version: 1.1
SGD	S000001245	is_active_in	GO:0005576	PMID:35123996	ECO:0000314			20220207	SGD		noctua-model-id=gomodel:61f34dd300000776|contributor=https://orcid.org/0000-0002-3726-7441|model-state=production
SGD	S000001245	enables	GO:0008253	PMID:35123996	ECO:0000250	P21589		20220207	SGD	part_of(GO:0019677),occurs_in(GO:0005576)	noctua-model-id=gomodel:61f34dd300000776|contributor=https://orcid.org/0000-0002-3726-7441|model-state=production
SGD	S000001245	involved_in	GO:0019677	PMID:35123996	ECO:0000315			20220207	SGD		noctua-model-id=gomodel:61f34dd300000776|contributor=https://orcid.org/0000-0002-3726-7441|model-state=production

Maybe it's because of the missing prefix in the 'with' field? Try changing P21589 to UniProtKB:P21589????

**Comment by suzialeksander** [comment]
Ooof, I'm almost certain that's it.  Good catch, thanks. Changed it and just waiting to see if it makes the trip through to SGD now.

**Comment by suzialeksander** [comment]
I suspect this was the problem

**Comment by ukemi** [comment]
Fingers crossed.
