### ISSUE TITLE
Mouse proteoform annotations are not in the GPAD file

### ISSUE THREAD

**Issue by kltm** [geneontology/minerva#78]
_Transferred from geneontology/noctua#384_

Hi @balhoff ,

Hopefully this is the right tracker for this issue. In this model:

http://noctua.berkeleybop.org/editor/graph/gomodel:581e072c00000473

Karen made this model and made annotations using PR:000049741. This represents a non-modified proteoform of a mouse gene. The annotation is not showing up in the production GPAD file even though with the current rules it should. The entity is in the MGI GPI file.

@krchristie

-David

**Comment by ukemi** [comment]
If it's any help, Karen also made a model where she annotated isoforms using PR identifiers that also corresponded to UniProtKB isoforms and those are in the GPAD file.

http://noctua.berkeleybop.org/editor/graph/gomodel:5745387b00001874

**Comment by balhoff** [comment]
Thanks for the additional info, @ukemi. I spent some time on this last night but haven't figured it out yet, I'll let you know when I figure something out.

**Comment by ukemi** [comment]
It looks like with the new build of NEO, these annotations are there. I think this one can be closed. To summarize what I think happened, Karen was able to fill in the PRO identifiers using the fields within an annoton and was somehow able to get around the autocomplete function. Her identifiers were saved, but they did not correspond to mouse genes because they hadn't been loaded into NEo yet.

**Comment by balhoff** [comment]
Thanks @ukemi. I just tried the GPAD export in Noctua and see it there as well. I'll close this.
